spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db-changelog.xml
    drop-first: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oe?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    miniIdle: 1
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
logging:
  level:
   com.oe.account.impl: debug
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.oe.account.entity
